// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Hyperboliq")>]
[<assembly: AssemblyDescriptionAttribute("Hyperboliq - Predictable SQL")>]
[<assembly: AssemblyProductAttribute("Hyperboliq")>]
[<assembly: AssemblyCopyrightAttribute("Copyright 2015 Fredrik Forssen")>]
[<assembly: AssemblyVersionAttribute("0.4.0")>]
[<assembly: AssemblyFileVersionAttribute("0.4.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Hyperboliq"
    let [<Literal>] AssemblyDescription = "Hyperboliq - Predictable SQL"
    let [<Literal>] AssemblyProduct = "Hyperboliq"
    let [<Literal>] AssemblyCopyright = "Copyright 2015 Fredrik Forssen"
    let [<Literal>] AssemblyVersion = "0.4.0"
    let [<Literal>] AssemblyFileVersion = "0.4.0"
