// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Hyperboliq.PostgreSQL")>]
[<assembly: AssemblyDescriptionAttribute("Hyperboliq.PostgreSQL - Hyperboliq adapter for PostgreSQL")>]
[<assembly: AssemblyProductAttribute("Hyperboliq.PostgreSQL")>]
[<assembly: AssemblyCopyrightAttribute("Copyright 2015 Fredrik Forssen")>]
[<assembly: AssemblyVersionAttribute("0.4.0")>]
[<assembly: AssemblyFileVersionAttribute("0.4.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Hyperboliq.PostgreSQL"
    let [<Literal>] AssemblyDescription = "Hyperboliq.PostgreSQL - Hyperboliq adapter for PostgreSQL"
    let [<Literal>] AssemblyProduct = "Hyperboliq.PostgreSQL"
    let [<Literal>] AssemblyCopyright = "Copyright 2015 Fredrik Forssen"
    let [<Literal>] AssemblyVersion = "0.4.0"
    let [<Literal>] AssemblyFileVersion = "0.4.0"
