// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Hyperboliq.SqlLite")>]
[<assembly: AssemblyDescriptionAttribute("Hyperboliq.SqlLite- Hyperboliq adapter for SqlLite")>]
[<assembly: AssemblyProductAttribute("Hyperboliq.SqlLite")>]
[<assembly: AssemblyCopyrightAttribute("Copyright 2015 Fredrik Forssen")>]
[<assembly: AssemblyVersionAttribute("0.3.1")>]
[<assembly: AssemblyFileVersionAttribute("0.3.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Hyperboliq.SqlLite"
    let [<Literal>] AssemblyDescription = "Hyperboliq.SqlLite- Hyperboliq adapter for SqlLite"
    let [<Literal>] AssemblyProduct = "Hyperboliq.SqlLite"
    let [<Literal>] AssemblyCopyright = "Copyright 2015 Fredrik Forssen"
    let [<Literal>] AssemblyVersion = "0.3.1"
    let [<Literal>] AssemblyFileVersion = "0.3.1"
