// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Hyperboliq.SqlServer")>]
[<assembly: AssemblyDescriptionAttribute("Hyperboliq.SqlServer - Hyperboliq adapter for SQL Server")>]
[<assembly: AssemblyProductAttribute("Hyperboliq.SqlServer")>]
[<assembly: AssemblyCopyrightAttribute("Copyright 2015 Fredrik Forssen")>]
[<assembly: AssemblyVersionAttribute("0.4.0")>]
[<assembly: AssemblyFileVersionAttribute("0.4.0")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Hyperboliq.SqlServer"
    let [<Literal>] AssemblyDescription = "Hyperboliq.SqlServer - Hyperboliq adapter for SQL Server"
    let [<Literal>] AssemblyProduct = "Hyperboliq.SqlServer"
    let [<Literal>] AssemblyCopyright = "Copyright 2015 Fredrik Forssen"
    let [<Literal>] AssemblyVersion = "0.4.0"
    let [<Literal>] AssemblyFileVersion = "0.4.0"
